# Site Configs
safe: true
lsi: false

name: Realschule D&uuml;sseldorf Golzheim
description: Homepage der Realschule D&uuml;sseldorf Golzheim
url: http://www.schulen.duesseldorf.de/rs-tersteegenstr/
markdown: redcarpet
markdown_ext:  md,markdown
pygments: true
permalink: /aktuell/:year/:month/:day/:title/
paginate: 5
schulname: Realschule Düsseldorf Golzheim Terstegenstraße

docs_0_9_0: /schule
schule: /schule
